* Knit
** Coffee compilation
'coffee' sources specify the main module to require on (after)
loading. Note however, that currently all modules found in the folder
are compiled even if they are not dependencies of the main module.

This is important if we want to run some action only after the require
function has been provided by the stitched scripts. For example:

1. Load jQuery from CDN
2. Load stiched scripts
3. Use require inside jQuery(function () {})

Would usually result in an error, because the stiched scripts have not
had time to execute to provide 'require'. Thus, the require usage
should be written such that it is run from the stiched scripts when
it has provided the require function.
** TODO Can compiler dependencies be optional? (Dropped from package.json)
** TODO Catch compile errors so restart isn't required
** TODO Allow custom mime types (for string/file in particular)
** TODO Make Stitch module resolve dependencies using detective
Only include those modules that the selected main source file actually
depends on. (Dependency does something like this).
** TODO Plug-in compilers? (In config file for example)
