* Knit
** Targets help
Targets are specified in a _knit.coffee file as:

exports.targets =
  'result.js': ['./', 'coffee']
  'app.css': ['./mystyles.less', 'less']
  'more/': ['./other', 'knit']
  'robots.txt': ['Disallow: *', 'string']
  'favicon.ico': ['./resources/favicon.ico', 'file']

In the above the more/ folder would need to have a _knit.coffee file
in it.
** Config help
Config is specified in a _knit.coffee file as:

exports.config =
  coffee:
    libs: []
  less:
    compress: false
** TODO Make coffee compiler support specifying a specific source file
Currently, only a directory of modules can be specified, we want to be
able to specify an individual file. This would get automatically
required by the resulting JavaScript file.

This is important if we want to run some action only after the require
function has been provided by the stitched scripts. For example:

1. Load jQuery from CDN
2. Load stiched scripts
3. Use require inside jQuery(function () {})

Would usually result in an error, because the stiched scripts have not
had time to execute to provide 'require'. Thus, the require usage
should be written such that it is run from the stiched scripts when
it has provided the require function.

Also, it would allow us to only include those modules which it
depends on (using detective).
** TODO Make Stitch module resolve dependencies using detective
Only include those modules that the selected main source file actually
depends on. (Dependency does something like this).
** TODO Fix config parameter handling (compress doesn't work)
Generally think through parameter handling (command line, settings,
ENV vars, defaults).
** TODO Default to compression when building and no compression when serving
** TODO Allow for variations of _knit.coffee (.knit, _knit probably)
** TODO Better error messages on missing _knit files
** TODO Write documentation
** TODO Allow specifying non-standard handlers in config file somehow
