// Generated by CoffeeScript 1.3.3
(function() {
  var listResources, p;

  p = require('path');

  listResources = function(resources) {
    var handlerOrResources, list, resource, _fn;
    list = [];
    _fn = function(resource, handlerOrResources) {
      var h, hor, r, _i, _j, _len, _len1, _ref, _ref1, _results, _results1;
      if (typeof handlerOrResources === 'function') {
        return list.push([resource, handlerOrResources]);
      } else if (handlerOrResources instanceof Array) {
        _results = [];
        for (_i = 0, _len = handlerOrResources.length; _i < _len; _i++) {
          hor = handlerOrResources[_i];
          _results.push((function(hor) {
            var h, r, _j, _len1, _ref, _ref1, _results1;
            _ref = listResources(hor);
            _results1 = [];
            for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
              _ref1 = _ref[_j], r = _ref1[0], h = _ref1[1];
              _results1.push(list.push([p.join(resource, r), h]));
            }
            return _results1;
          })(hor));
        }
        return _results;
      } else if (typeof handlerOrResources === 'object') {
        _ref = listResources(handlerOrResources);
        _results1 = [];
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          _ref1 = _ref[_j], r = _ref1[0], h = _ref1[1];
          _results1.push(list.push([p.join(resource, r), h]));
        }
        return _results1;
      }
    };
    for (resource in resources) {
      handlerOrResources = resources[resource];
      _fn(resource, handlerOrResources);
    }
    return list;
  };

  exports.flatten = function(resources) {
    var flatResources, handler, resource, _i, _len, _ref, _ref1;
    flatResources = {};
    _ref = listResources(resources);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], resource = _ref1[0], handler = _ref1[1];
      flatResources[resource] = handler;
    }
    return flatResources;
  };

  exports.module = function(module, action, knit, log) {
    if ((typeof module.resources) === 'function') {
      return exports.flatten(module.resources(action, knit, log));
    } else {
      return exports.flatten(module.resources);
    }
  };

}).call(this);
